WITH Rare_Items AS (
    SELECT ITEM_ID
    FROM ITEM_INFO
    WHERE RARITY = 'RARE'
)

SELECT DISTINCT
    I.ITEM_ID,
    I.ITEM_NAME,
    I.RARITY
FROM
    ITEM_TREE T
JOIN 
    Rare_Items R ON T.PARENT_ITEM_ID = R.ITEM_ID
JOIN 
    ITEM_INFO I ON T.ITEM_ID = I.ITEM_ID
ORDER BY 
    I.ITEM_ID DESC;