SELECT
    ROUTE, 
    CONCAT(ROUND(sum(D_BETWEEN_DIST), 1), 'km') as TOTAL_DISTANCE, 
    CONCAT(ROUND(sum(D_BETWEEN_DIST)/count(*), 2), 'km') as AVERAGE_DISTANCE
FROM
    SUBWAY_DISTANCE 
GROUP BY
    ROUTE
ORDER BY sum(D_BETWEEN_DIST) desc