WITH EMP_SCORE AS (
    SELECT 
        EMP_NO,
        SUM(SCORE) as SCORE
    FROM
        HR_GRADE
    WHERE
        YEAR = '2022'
    GROUP BY EMP_NO
)

SELECT
    ES.SCORE,
    E.EMP_NO,
    E.EMP_NAME,
    E.POSITION,
    E.EMAIL
FROM
    EMP_SCORE as ES JOIN HR_EMPLOYEES as E on ES.EMP_NO = E.EMP_NO
WHERE
    ES.SCORE = (SElECT MAX(SCORE) FROM EMP_SCORE)