WITH RANKED_COLONY AS (
    SELECT 
        ID,
        SIZE_OF_COLONY,
        NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS RANKED
    FROM 
        ECOLI_DATA
)


SELECT
    ID,
    CASE
        WHEN RANKED = 1 THEN 'CRITICAL'
        WHEN RANKED = 2 THEN 'HIGH'
        WHEN RANKED = 3 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME 
FROM 
    RANKED_COLONY
ORDER BY
    ID ASC
